services:
  - type: web
    name: backend
    env: node
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString

databases:
  - name: my-database
    plan: free
