ALTER TABLE properties
ALTER COLUMN reference_number DROP DEFAULT;

DROP TRIGGER IF EXISTS trigger_update_property_reference_number ON properties;
DROP FUNCTION IF EXISTS update_property_reference_number();

COMMENT ON COLUMN properties.reference_number IS
  'Manually entered unique property reference number. It is no longer auto-generated by the database.';
